### ISSUE TITLE
No Wallet Endpoint

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/wormholecash#2]
The [third wormhole tutorial](https://developer.bitcoin.com/tutorials/wormhole-3-tokens.html) discusses the ` wallet/newAddress` endpoint. I see the [wormholerest repo](https://github.com/Bitcoin-com/wormholerest.bitcoin.com/blob/master/routes/wallet.js) was expanded go include a wallet endpoint. Probably to support the tutorial.

However, there is currently no support for the `wallet/newAddress` endpoint in this SDK.

**Comment by mauhcs** [comment]
I can see this endpoint in my screen. 
It is the first method.

![screen shot 2018-08-21 at 9 24 46](https://user-images.githubusercontent.com/17294645/44373425-1684ae80-a524-11e8-89b3-af5f72a59813.png)

**Comment by christroutner** [comment]
Right. The endpoint exists in the [wormholerest repository](https://github.com/Bitcoin-com/wormholerest.bitcoin.com/blob/master/routes/wallet.js). But that endpoint is currently not supported by the [wormholecash sdk](https://github.com/Bitcoin-com/wormholecash/tree/master/src).

**Comment by cgcardona** [comment]
This is resolved in `wormholecash` v0.3.1

https://developer.bitcoin.com/wormhole/docs/wallet.html

**Comment by alexdovzhanyn** [comment]
I'm still experiencing this issue today, not seeing anything related to wallet on my screen. I have the Digital Ocean droplet set up and running, fully synced, but when I connect through WormholeREST I don't see any wallet endpoints. Also, as a sidenote, I'm getting a 404 when trying to access [https://developer.bitcoin.com/wormhole/docs/wallet.html](https://developer.bitcoin.com/wormhole/docs/wallet.html) or any of the pages under /docs.

**Comment by alexdovzhanyn** [comment]
Nevermind, this seems to be an issue with a different repository: [https://github.com/Bitcoin-com/wormholerest.bitcoin.com](https://github.com/Bitcoin-com/wormholerest.bitcoin.com). Sorry for the noise!

**Comment by christroutner** [comment]
@alexdovzhanyn wormholerest has been depricated. I responded to your forum post:
https://forum.bitcoin.com/topic97833.html
